config/routes.rb
Circular::Application.routes.draw do
  resources :templates

  resources :sidearticles

  resources :authors

  resources :articles

  resources :newsletters

  root :to => 'newsletters#index'

end

app/views/templates/_form.html.haml
= form_for @template do |f|
  - if @template.errors.any?
    #error_explanation
      %h2= "#{pluralize(@template.errors.count, "error")} prohibited this template from being saved:"
      %ul
        - @template.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :html
    = f.text_field :html
  .actions
    = f.submit 'Save'

app/views/templates/edit.html.haml
%h1 Editing template

= render 'form'

= link_to 'Show', @template
\|
= link_to 'Back', templates_path

app/views/templates/index.html.haml
%h1 Listing templates

%table
  %tr
    %th Name
    %th Html
    %th
    %th
    %th

  - @templates.each do |template|
    %tr
      %td= template.name
      %td= template.html
      %td= link_to 'Show', template
      %td= link_to 'Edit', edit_template_path(template)
      %td= link_to 'Destroy', template, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Template', new_template_path

app/views/templates/new.html.haml
%h1 New template

= render 'form'

= link_to 'Back', templates_path

app/views/templates/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @template.name
%p
  %b Html:
  = @template.html

= link_to 'Edit', edit_template_path(@template)
\|
= link_to 'Back', templates_path