config/routes.rb
Circular::Application.routes.draw do
  resources :templates

  resources :sidearticles

  resources :authors

  resources :articles

  resources :newsletters

  root :to => 'newsletters#index'

end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
  has_many :articles, order: "position ASC", dependent: :destroy
  has_many :sidearticles, order: "position ASC", dependent: :destroy
  attr_accessible :author_id, :code, :content, :show_dividerline, :show_outline, :status_id, :template_id, :topic, :articles_attributes, :sidearticles_attributes
  belongs_to :template
  belongs_to :author
  accepts_nested_attributes_for :articles, allow_destroy: true
  accepts_nested_attributes_for :sidearticles, allow_destroy: true
end

app/controllers/newsletters_controller.rb
class NewslettersController < ApplicationController
  # GET /newsletters
  # GET /newsletters.json
  def index
    @newsletters = Newsletter.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @newsletters }
    end
  end

  # GET /newsletters/1
  # GET /newsletters/1.json
  def show
    @newsletter = Newsletter.find(params[:id])
    if params[:download]
        send_data(@newsletter.code, :filename => @newsletter.topic+".html", :type => "text/html")
    else
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @newsletter }
      end
    end
  end

  # GET /newsletters/new
  # GET /newsletters/new.json
  def new
    @newsletter = Newsletter.new
    @templates = Template.all
    @authors = Author.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @newsletter }
    end
  end

  # GET /newsletters/1/edit
  def edit
    @newsletter = Newsletter.find(params[:id])
    @templates = Template.all
    @authors = Author.all
  end


  # POST /newsletters
  # POST /newsletters.json
  def create
    @newsletter = Newsletter.new(params[:newsletter])
    @templates = Template.all
    @authors = Author.all

    respond_to do |format|
      if @newsletter.save
        format.html { redirect_to action: "index" }
        # format.html { redirect_to @newsletter, notice: 'Newsletter was successfully created.' }
        format.json { render json: @newsletter, status: :created, location: @newsletter }
      else
        format.html { render action: "new" }
        format.json { render json: @newsletter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /newsletters/1
  # PUT /newsletters/1.json
  def update
    @newsletter = Newsletter.find(params[:id])

    respond_to do |format|
      if @newsletter.update_attributes(params[:newsletter])
        format.html { redirect_to action: "index" }
        # format.html { redirect_to @newsletter, notice: 'Newsletter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @newsletter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /newsletters/1
  # DELETE /newsletters/1.json
  def destroy
    @newsletter = Newsletter.find(params[:id])
    @newsletter.destroy

    respond_to do |format|
      format.html { redirect_to newsletters_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/newsletters_helper.rb
module NewslettersHelper
end

app/views/newsletters/_article_fields.html.erb
<div class="well article">
	<%= f.hidden_field :position %>
	<div class="control-group">
		<%= f.label :topic, "Headline" %>
		<div class="controls">
			<%= f.text_field :topic, class: "input-block-level article_headline" %>
		</div>
	</div>
	<div class="control-group">
		<%= f.label :content, "Text" %>
		<div class="controls">
			<%= f.text_area :content, class: "input-block-level article_text" %>
		</div>
	</div>
	<div class="control-group">
		<div class="controls">
			<%= f.hidden_field :show_dividerline? %>
			<%= f.button("Show Divider Line", {:class => f.object.show_dividerline ? 'btn active' : 'btn', :'data-toggle' => 'button', :type => 'button'}) %>
		</div>
	</div>
	<div class="control-group">
		<div class="controls">
			<%= f.hidden_field :_destroy %>
			<%= link_to raw("<i class='icon-trash'></i>"), '#', class: "remove_fields btn btn-mini btn-danger" %>
			<%= link_to raw("<i class='icon-arrow-up'></i>"), '#', class: "move_up btn btn-mini" %>
			<%= link_to raw("<i class='icon-arrow-down'></i>"), '#', class: "move_down btn btn-mini" %>
		</div>
	</div>
</div>

app/views/newsletters/_articles.html.erb
<fieldset id="articles">
  <legend>Articles</legend>
  <%= f.fields_for :articles do |article_form| %>
    <%= render 'article_fields',  :f => article_form  %>
  <% end %>
  <%= link_to_add_fields raw("<i class='icon-plus-sign'></i> Add Article"), f, :articles %>
</fieldset>

app/views/newsletters/_form.html.erb
<%= form_for(@newsletter, :html => { :class => "form-horizontal newsletter-form"}) do |f| %>
<% if @newsletter.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@newsletter.errors.count, "error") %> prohibited this newsletter from being saved:</h2>

  <ul>
    <% @newsletter.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>


<fieldset id="general-settings">

  <legend>General Settings</legend>

  <div class="control-group">
    <%= f.hidden_field :id %>
    <%= f.label :topic %>
    <div class="controls">
      <%= f.text_field :topic, class: 'input-block-level' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :content %>
    <div class="controls">
      <%= f.text_area :content, class: 'newsletter_text' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :template_id %>
    <div class="controls">
      <%= f.collection_select(:template_id, @templates, :id, :name) %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :author_id %>
    <div class="controls">
      <%= f.collection_select(:author_id, @authors, :id, :name) %>
    </div>
  </div>
  <div class="control-group">     
    <div class="controls">
      <%= f.hidden_field :show_outline? %>
      <%= f.button("Outline", {:class => @newsletter.show_outline ? 'btn active' : 'btn', :'data-toggle' => 'button', :type => 'button', :name => 'newsletter[show_outline]'}) %>
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
      <%= f.hidden_field :show_dividerline? %>
      <%= f.button("Divider Line", {:class => @newsletter.show_dividerline ? 'btn active' : 'btn', :'data-toggle' => 'button', :type => 'button', :name => 'newsletter[show_dividerline]'}) %>
    </div>
  </div>

</fieldset>




<%= render 'articles', f: f %>
<%= render 'sidearticles', f: f %>



<%= f.hidden_field :code %>
<div class="actions">
  <%= link_to("Save", {}, {:href => "#", :class => "submit btn btn-success save"}) %>
  <%= f.submit "Save and Exit", {:class => 'submit btn btn-success save-and-exit'} %>

</div>

<% end %>

app/views/newsletters/_sidearticle_fields.html.erb
<div class="well sidearticle">
  <%= f.hidden_field :position %>
  <div class="control-group">
    <%= f.label :topic, "Headline" %>
    <div class="controls">
      <%= f.text_field :topic, class: "input-block-level sidearticle_headline" %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :content, "Text" %>
    <div class="controls">
      <%= f.text_area :content, class: "input-block-level sidearticle_text" %>
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
      <%= f.hidden_field :_destroy %>
      <%= link_to raw("<i class='icon-trash'></i>"), '#', class: "remove_fields btn btn-mini btn-danger" %>
      <%= link_to raw("<i class='icon-arrow-up'></i>"), '#', class: "move_up btn btn-mini" %>
      <%= link_to raw("<i class='icon-arrow-down'></i>"), '#', class: "move_down btn btn-mini" %>
    </div>
  </div>
</div>

app/views/newsletters/_sidearticles.html.erb
<fieldset id="sidearticles">
  <legend>Side Articles</legend>
  <%= f.fields_for :sidearticles do |sidearticle_form| %>
    <%= render 'sidearticle_fields',  :f => sidearticle_form  %>
  <% end %>
  <%= link_to_add_fields raw("<i class='icon-plus-sign'></i> Add Side Article"), f, :sidearticles %>
</fieldset>

app/views/newsletters/edit.html.erb
<h3>Editing Newsletter <%= @newsletter.id %></h3>


<div class="row-fluid">
	<div class="span6 form">
		<%= render 'form' %>
	</div>


	<div class="span6 newsletter">
		<div class="preiframe">
			<ul class="nav nav-tabs">
				<li class="active" id="preview">
					<a href="#">Preview</a>
				</li>
				<li id="code"><a href="#">Code</a></li>
			</ul>

			<iframe id ="iframe">
			</iframe>
			<div id="precontainer">
				<pre id="pre" class="pre-scrollable"></pre>
			</div>
		</div>

	</div><!--/span-->

app/views/newsletters/index.html.erb
<h1>Newsletters</h1>

<table id="newsletter_list" class="newsletter_list table table-striped table-hover">
    <thead>
      <tr>
        <th class="number">id</th>
        <th>Topic</th>
        <th>Author</th>
        <th>Updated</th>
        <th class="actions"></th>
      </tr>
    </thead>

    <tbody>
        <% @newsletters.each do |newsletter| %>
          <tr>
            <td><%= newsletter.id %></td>
            <td><%= newsletter.topic %></td>
            <td><%= newsletter.author.try :name %></td>
            <td><%= time_ago_in_words(newsletter.updated_at) %>
                ago
                <%= newsletter.updated_at.strftime('(%Y-%m-%d %H:%M:%S)') %></td>
            <td>
                    
                <%= link_to edit_newsletter_path(newsletter) do %>
                    <button  class="btn btn-mini edit" title="Edit"><i class="icon-pencil"></i></button>
                <% end %>
                <%= link_to newsletter do %>
                    <button  class="btn btn-mini properties" title="Properties"><i class="icon-list"></i></button>
                <% end %>
                <%= link_to newsletter_path(newsletter, :download => true) do %>
                    <button  class="btn btn-mini download" title="Download"><i class="icon-download"></i></button>
                <% end %>
                <%= link_to newsletter, method: :delete, data: { confirm: 'Are you sure?' } do %>
                    <button class="btn btn-mini danger delete" data-toggle="modal" title="Delete"><i class="icon-trash"></i></button>
                <% end %>
            </td>
          </tr>
        <% end %>
    </tbody>
</table>

<br />

<%= link_to raw("<button class='btn'><i class='icon-plus-sign'></i> Create Newsletter</button>"), new_newsletter_path %>

app/views/newsletters/new.html.erb
<h3>New Newsletter</h3>

<div class="row-fluid">
	<div class="span6 form">
		<%= render 'form' %>
	</div>


	<div class="span6 newsletter">
		<div class="preiframe">
			<ul class="nav nav-tabs">
				<li class="active" id="preview">
					<a href="#">Preview</a>
				</li>
				<li id="code"><a href="#">Code</a></li>
			</ul>

			<iframe id ="iframe">
			</iframe>
			<div id="precontainer">
				<pre id="pre" class="pre-scrollable"></pre>
			</div>
		</div>

	</div><!--/span-->

app/views/newsletters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Topic:</b>
  <%= @newsletter.topic %>
</p>

<p>
  <b>Content:</b>
  <%= @newsletter.content %>
</p>

<p>
  <b>Author:</b>
  <%= @newsletter.author_id %>
</p>

<p>
  <b>Template:</b>
  <%= @newsletter.template_id %>
</p>

<p>
  <b>Status:</b>
  <%= @newsletter.status_id %>
</p>

<p>
  <b>Show outline:</b>
  <%= @newsletter.show_outline %>
</p>

<p>
  <b>Code:</b>
  <%= @newsletter.code %>
</p>

<p>
  <b>Show dividerline:</b>
  <%= @newsletter.show_dividerline %>
</p>


<%= link_to 'Edit', edit_newsletter_path(@newsletter) %> |
<%= link_to 'Back', newsletters_path %>