config/routes.rb
Circular::Application.routes.draw do
  resources :templates

  resources :sidearticles

  resources :authors

  resources :articles

  resources :newsletters

  root :to => 'newsletters#index'

end

app/models/sidearticle.rb
class Sidearticle < ActiveRecord::Base
  belongs_to :newsletter
  attr_accessible :content, :position, :topic, :newsletter_id
  # validates :newsletter, presence: true # raises error in nested forms
end

app/controllers/sidearticles_controller.rb
class SidearticlesController < ApplicationController
  # GET /sidearticles
  # GET /sidearticles.json
  def index
    @sidearticles = Sidearticle.order("position")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sidearticles }
    end
  end

  # GET /sidearticles/1
  # GET /sidearticles/1.json
  def show
    @sidearticle = Sidearticle.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sidearticle }
    end
  end

  # GET /sidearticles/new
  # GET /sidearticles/new.json
  def new
    @sidearticle = Sidearticle.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sidearticle }
    end
  end

  # GET /sidearticles/1/edit
  def edit
    @sidearticle = Sidearticle.find(params[:id])
  end

  # POST /sidearticles
  # POST /sidearticles.json
  def create
    @sidearticle = Sidearticle.new(params[:sidearticle])

    respond_to do |format|
      if @sidearticle.save
        format.html { redirect_to @sidearticle, notice: 'Sidearticle was successfully created.' }
        format.json { render json: @sidearticle, status: :created, location: @sidearticle }
      else
        format.html { render action: "new" }
        format.json { render json: @sidearticle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sidearticles/1
  # PUT /sidearticles/1.json
  def update
    @sidearticle = Sidearticle.find(params[:id])

    respond_to do |format|
      if @sidearticle.update_attributes(params[:sidearticle])
        format.html { redirect_to @sidearticle, notice: 'Sidearticle was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sidearticle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sidearticles/1
  # DELETE /sidearticles/1.json
  def destroy
    @sidearticle = Sidearticle.find(params[:id])
    @sidearticle.destroy

    respond_to do |format|
      format.html { redirect_to sidearticles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/sidearticles_helper.rb
module SidearticlesHelper
end

app/views/sidearticles/_form.html.haml
= form_for @sidearticle do |f|
  - if @sidearticle.errors.any?
    #error_explanation
      %h2= "#{pluralize(@sidearticle.errors.count, "error")} prohibited this sidearticle from being saved:"
      %ul
        - @sidearticle.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :topic
    = f.text_field :topic
  .field
    = f.label :content
    = f.text_area :content
  .field
    = f.label :newsletter
    = f.text_field :newsletter
  .field
    = f.label :position
    = f.number_field :position
  .actions
    = f.submit 'Save'

app/views/sidearticles/edit.html.haml
%h1 Editing sidearticle

= render 'form'

= link_to 'Show', @sidearticle
\|
= link_to 'Back', sidearticles_path

app/views/sidearticles/index.html.haml
%h1 Listing sidearticles

%table
  %tr
    %th Topic
    %th Content
    %th Newsletter
    %th Position
    %th
    %th
    %th

  - @sidearticles.each do |sidearticle|
    %tr
      %td= sidearticle.topic
      %td= sidearticle.content
      %td= sidearticle.newsletter
      %td= sidearticle.position
      %td= link_to 'Show', sidearticle
      %td= link_to 'Edit', edit_sidearticle_path(sidearticle)
      %td= link_to 'Destroy', sidearticle, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Sidearticle', new_sidearticle_path

app/views/sidearticles/new.html.haml
%h1 New sidearticle

= render 'form'

= link_to 'Back', sidearticles_path

app/views/sidearticles/show.html.haml
%p#notice= notice

%p
  %b Topic:
  = @sidearticle.topic
%p
  %b Content:
  = @sidearticle.content
%p
  %b Newsletter:
  = @sidearticle.newsletter
%p
  %b Position:
  = @sidearticle.position

= link_to 'Edit', edit_sidearticle_path(@sidearticle)
\|
= link_to 'Back', sidearticles_path